# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nextjsV1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mediavalet.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f9d3a515b6d14111b1d3bf2e6848f624 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c07b564cf6d343468f843da155a7381c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mediavalet.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f9d3a515b6d14111b1d3bf2e6848f624 }}/nextcontentful:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nextjsV1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_88ffa3533c59411f8803fff1dcc8b6ce }}
        images: 'mediavalet.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f9d3a515b6d14111b1d3bf2e6848f624 }}/nextcontentful:${{ github.sha }}'